version: '3.8'

services:
  app:
    build: .
    container_name: event-booking-app
    ports:
      - '3000:3000'
    depends_on:
      - booking-db
      - redis
    env_file:
      - .env
    networks:
      - event-booking-network
    volumes:
      - .:/usr/src/app
    restart: always

  booking-db:
    image: postgres:15
    container_name: booking-db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - event-booking-network
    command: ["postgres", "-c", "listen_addresses=*"]

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - event-booking-network

networks:
  event-booking-network:

volumes:
  db-data:
